-- Course Cancellation Form Table
CREATE TABLE IF NOT EXISTS `course_cancellations` (
  `cancellation_id` int(11) NOT NULL AUTO_INCREMENT,
  `cancellation_unique_id` varchar(255) DEFAULT NULL,
  `title` varchar(10) DEFAULT NULL,
  `family_name` varchar(255) NOT NULL,
  `given_names` varchar(255) NOT NULL,
  `residential_address` varchar(500) NOT NULL,
  `post_code` varchar(10) NOT NULL,
  `contact_number` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` varchar(1) DEFAULT NULL,
  `course_code` varchar(255) DEFAULT NULL,
  `course_title` varchar(500) DEFAULT NULL,
  `date_of_enrolment` date DEFAULT NULL,
  `reason_for_cancellation` varchar(255) DEFAULT NULL,
  `reason_other_details` text DEFAULT NULL,
  `cancellation_effective_date` date DEFAULT NULL,
  `cooling_off_period` varchar(10) DEFAULT NULL,
  `account_type` varchar(20) DEFAULT NULL,
  `bank_name` varchar(255) DEFAULT NULL,
  `bsb` varchar(10) DEFAULT NULL,
  `account_number` varchar(50) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `signature` varchar(255) DEFAULT NULL,
  `submission_date` date DEFAULT NULL,
  `refund_to_be_issued` varchar(10) DEFAULT NULL,
  `refund_approved_by` varchar(255) DEFAULT NULL,
  `refund_approved_date` date DEFAULT NULL,
  `refund_amount` decimal(10,2) DEFAULT NULL,
  `date_forwarded_to_finance` date DEFAULT NULL,
  `finance_initial` varchar(255) DEFAULT NULL,
  `office_comments` text DEFAULT NULL,
  `status` tinyint(1) DEFAULT 0,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `modified_date` date DEFAULT NULL,
  `modified_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`cancellation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Course Extension Form Table
CREATE TABLE IF NOT EXISTS `course_extensions` (
  `extension_id` int(11) NOT NULL AUTO_INCREMENT,
  `extension_unique_id` varchar(255) DEFAULT NULL,
  `title` varchar(10) DEFAULT NULL,
  `family_name` varchar(255) NOT NULL,
  `given_names` varchar(255) NOT NULL,
  `residential_address` varchar(500) NOT NULL,
  `post_code` varchar(10) NOT NULL,
  `contact_number` varchar(20) NOT NULL,
  `email` varchar(255) NOT NULL,
  `course_code` varchar(255) DEFAULT NULL,
  `course_title` varchar(500) DEFAULT NULL,
  `enrolment_date` date DEFAULT NULL,
  `reason_for_extension` varchar(255) DEFAULT NULL,
  `reason_other_details` text DEFAULT NULL,
  `extension_duration` varchar(255) DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `signature` varchar(255) DEFAULT NULL,
  `submission_date` date DEFAULT NULL,
  `extension_approved` varchar(10) DEFAULT NULL,
  `application_approved_by` varchar(255) DEFAULT NULL,
  `approval_initial` varchar(255) DEFAULT NULL,
  `approval_date` date DEFAULT NULL,
  `rollover_fee` decimal(10,2) DEFAULT NULL,
  `office_comments` text DEFAULT NULL,
  `status` tinyint(1) DEFAULT 0,
  `created_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `created_by` int(11) DEFAULT NULL,
  `modified_date` date DEFAULT NULL,
  `modified_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`extension_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
